# Generated by Django 4.2.6 on 2023-11-11 16:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('url', models.CharField(max_length=141, null=True)),
                ('telephone', models.CharField(max_length=80, null=True)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('addressreg', models.CharField(max_length=80, null=True)),
                ('addressloc', models.CharField(max_length=80, null=True)),
                ('addresscou', models.CharField(max_length=80, null=True)),
                ('tags', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
    ]
